### ISSUE TITLE
Gru seemingly does not work with JDK11

### ISSUE THREAD

**Issue by ysb33r** [agorapulse/gru#36]
We recently upgraded a Microanut project from JDK8 to JDK11 and most of our unit tests failed with 

```
java.lang.IncompatibleClassChangeError: Method 'java.util.function.Function java.util.function.Function.identity()' must be InterfaceMethodref constant
            at com.agorapulse.gru.minions.JsonMinion.<init>(JsonMinion.groovy:31)
            at java.base/java.lang.Class.newInstance(Class.java:584)
            at com.agorapulse.gru.Squad.findOrCreateMinionByType(Squad.java:79)
            at com.agorapulse.gru.Squad.command(Squad.java:71)
            at com.agorapulse.gru.DefaultRequestDefinitionBuilder.command(DefaultRequestDefinitionBuilder.java:26)
            at com.agorapulse.gru.DefaultRequestDefinitionBuilder.json(DefaultRequestDefinitionBuilder.java:32)
            at com.agorapulse.gru.DefaultRequestDefinitionBuilder.json(DefaultRequestDefinitionBuilder.java:37)
            at com.agorapulse.gru.DefaultRequestDefinitionBuilder.json(DefaultRequestDefinitionBuilder.java:16)
```

The error all point to https://github.com/agorapulse/gru/blob/1ba2378ef84e2572bc216b0ec29b352032aac32a/gru/src/main/groovy/com/agorapulse/gru/minions/JsonMinion.groovy#L31.

If it is of any help, all of the failing Spock tests have the following kind of structure:

```groovy
@MicronautTest(environments = ['development'], application = Application)
class SomeSpec extends Specification {

    @Rule
    Gru gru = Gru.equip(ApiGatewayProxy.steal(this) {
        map '/some/path'' to StreamLambdaHandler
    })

    @Rule
    Dru dru = Dru.steal(this)

    void 'some test'() {
        expect:
        gru.test {
            get '/some/path'
            expect {
                status 200
                json 'expected-response.json'
            }
        }
    }
}
```

**Comment by musketyr** [comment]
can you build this branch locally and test if it solves the issue?

https://github.com/agorapulse/gru/tree/fix/java-11-compatibility

**Comment by ysb33r** [comment]
@musketyr looks like it works.

**Comment by musketyr** [comment]
should be fixed in `0.8.4`, let me know if you find any other blocker. there's a lot of work ahead as well to support Spock 2 and JUnit 5 but I will have to get some more bandwidth for this.

**Comment by gregorydickson** [comment]
@musketyr @ysb33r Validated it works. +1 on the move to Junit 5 as Micronaut/Test appear to have removed Junit 4 dependencies.

**Comment by musketyr** [comment]
thanks for the feedback. I'm closing the issue now
